s = input()

print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.swapcase())
print(s.swapcase().upper())
print(s.swapcase().lower())
print(s.title())
print(s.split())
print(s.replace('r','a'))