a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

print("Sum:",a+b )
print("Difference:",a-b )
print("Product:",a*b )
print("Division:", a/b)
print("Floor Division:",a//b )
print("Modulus:",a%b )
print("Power:", a**b)
